In [2]:
import numpy as np

In [3]:
data = np.array([1, 2, 3])

In [5]:
data = list(range(10))

In [6]:
print(data)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [9]:
a = data[:5]
print(a)
a = np.random.randn(4, 5)
print(a)

[0, 1, 2, 3, 4]
[[-1.35689574  0.35159703  0.64261347 -1.62945903  0.28417218]
 [-0.52461598 -0.33302442  0.02318553  1.03821419 -0.16707382]
 [-0.03403532 -0.15500042 -0.84108398  0.97926988 -1.18554875]
 [ 0.36432909  0.23620014 -1.01265841 -0.4576284   0.24703764]]


In [12]:
a = np.arange(10)
for i in a:
    print(i)

0
1
2
3
4
5
6
7
8
9
