In [1]:
import numpy as np

In [2]:
data = np.array([1, 2, 3])

In [3]:
data = list(range(10))

In [4]:
print(data)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [5]:
a = data[:5]
print(a)
a = np.random.randn(4, 5)
print(a)

[0, 1, 2, 3, 4]
[[ 1.47222003 -0.29852305 -0.26024829 -0.31064892 -1.44749973]
 [-0.6419655   1.43037813  1.68745455 -0.82314864  1.78417989]
 [-1.73698901  0.78577454  0.41215694  0.26306632 -0.72782006]
 [ 1.02254104  2.8875027  -1.42657148  0.78884925 -1.04086983]]


In [6]:
a = np.arange(10)
for i in a:
    print(i)

0
1
2
3
4
5
6
7
8
9
